name: 'Install Verathread CLI'
description: 'Installs the Verathread CLI'
inputs:
  version:
    description: 'Version of the CLI to install, leaving this empty will install the latest version'
    required: false
runs:
  using: "composite"
  steps:
    - name: "Install Verathread CLI"
      shell: bash
      working-directory: ${{ github.action_path }}
      if: inputs.version != ''
      run: |
        export TAG=${{ inputs.version }}
        wget -q -O - https://vth-artifacts.s3-eu-west-1.amazonaws.com/cli_v2/install.sh | bash

    - name: "Install Verathread CLI"
      shell: bash
      working-directory: ${{ github.action_path }}
      if: inputs.version == ''
      run: |
        wget -q -O - https://vth-artifacts.s3-eu-west-1.amazonaws.com/cli_v2/install.sh | bash
